name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build-and-release:
    strategy:
      matrix:
        include:
          - runner: macos-14
            target: aarch64-apple-darwin
            suffix: darwin-aarch64
          - runner: macos-latest
            target: x86_64-apple-darwin
            suffix: darwin-x86_64
    runs-on: ${{ matrix.runner }}

    steps:
      - uses: actions/checkout@v4
      
      - name: Install OpenSSL
        run: |
          brew install openssl@3
          echo "OPENSSL_DIR=$(brew --prefix openssl@3)" >> $GITHUB_ENV
      
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      - name: Prepare binary
        run: |
          cp target/${{ matrix.target }}/release/gyst gyst-${{ matrix.suffix }}

      - name: Generate SHA256
        run: |
          shasum -a 256 gyst-${{ matrix.suffix }} > gyst-${{ matrix.suffix }}.sha256

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false
          files: |
            gyst-${{ matrix.suffix }}
            gyst-${{ matrix.suffix }}.sha256
          generate_release_notes: true
